// Auto-generated by gen_font_blob.py — do not edit (source: fonts/Conthrax-SemiBold.otf)
// sha256:625c8da7e5e1937a  template:v1  bytes:77528
// Rasterized at runtime by LVGL TinyTTF (main/ui_fonts/ui_fonts.c);
// sizing per render resolution lives in ui_fonts_logic.h.
#pragma once
#include <stdint.h>

#define UI_CONTHRAX_OTF_SIZE 77528
extern const uint8_t ui_conthrax_otf_data[UI_CONTHRAX_OTF_SIZE];
