#!/usr/bin/env python3
"""gen_font_blob.py — Conthrax OTF → 固件内嵌 C 数组(TinyTTF 运行时栅格化)。

源字体 fonts/Conthrax-SemiBold.otf 原样嵌入 main/ui_fonts/conthrax_otf.c,
配对头文件 contrax_otf.h 提供数组声明与长度宏;栅格化由 LVGL TinyTTF 在
设备/模拟器上按需完成(见 main/ui_fonts/ui_fonts.c),字号按渲染分辨率
运行时计算,不再有 per-res 生成物。

用法:
    python3 tools/gen_font_blob.py            # 生成(OTF 变更后重跑)
    python3 tools/gen_font_blob.py --check    # 新鲜度校验,只读(零依赖,CI 用)
"""
import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_SOURCE = ROOT / "fonts" / "Conthrax-SemiBold.otf"
OUT_DIR = ROOT / "main" / "ui_fonts"
OUT_C = OUT_DIR / "conthrax_otf.c"
OUT_H = OUT_DIR / "conthrax_otf.h"
GENERATED_MARKER = "Auto-generated by gen_font_blob.py"
TEMPLATE_VERSION = "v1"   # bump when output format changes


def render(data: bytes) -> "tuple[str, str]":
    otf_sha = hashlib.sha256(FONT_SOURCE.read_bytes()).hexdigest()[:16]
    chunks = [", ".join(f"0x{b:02X}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    header = (
        f"// {GENERATED_MARKER} — do not edit (source: fonts/Conthrax-SemiBold.otf)\n"
        f"// sha256:{otf_sha}  template:{TEMPLATE_VERSION}  bytes:{len(data)}\n"
        "// Rasterized at runtime by LVGL TinyTTF (main/ui_fonts/ui_fonts.c);\n"
        "// sizing per render resolution lives in ui_fonts_logic.h.\n"
    )
    h_text = (
        header
        + "#pragma once\n#include <stdint.h>\n\n"
        + f"#define UI_CONTHRAX_OTF_SIZE {len(data)}\n"
        + "extern const uint8_t ui_conthrax_otf_data[UI_CONTHRAX_OTF_SIZE];\n"
    )
    c_text = (
        header
        + '#include "conthrax_otf.h"\n\n'
        + "const uint8_t ui_conthrax_otf_data[UI_CONTHRAX_OTF_SIZE] = {\n"
        + "  " + ",\n  ".join(chunks) + "\n};\n"
    )
    return h_text, c_text


def write_if_changed(path: Path, text: str) -> bool:
    if not path.exists() or path.read_text() != text:
        path.write_text(text)
        print(f"  wrote {path.relative_to(ROOT)}")
        return True
    return False


def generate() -> int:
    if not FONT_SOURCE.exists():
        print(f"missing font source: {FONT_SOURCE}")
        return 1
    h_text, c_text = render(FONT_SOURCE.read_bytes())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    changed = write_if_changed(OUT_H, h_text)
    changed |= write_if_changed(OUT_C, c_text)
    print("gen_font_blob: generation done" if changed else "gen_font_blob: up to date")
    return 0


def check() -> int:
    """零第三方依赖——校验输出存在且头部记录的源 SHA / 模板版本一致。"""
    if not FONT_SOURCE.exists():
        print(f"missing font source: {FONT_SOURCE}")
        return 1
    otf_sha = hashlib.sha256(FONT_SOURCE.read_bytes()).hexdigest()[:16]
    problems = []
    for out in (OUT_H, OUT_C):
        if not out.exists():
            problems.append(f"missing: {out.relative_to(ROOT)}")
            continue
        text = out.read_text()
        for needle in (f"sha256:{otf_sha}", f"template:{TEMPLATE_VERSION}"):
            if needle not in text:
                problems.append(f"stale: {out.relative_to(ROOT)} (no {needle})")
    if problems:
        print("\n".join(problems))
        print("run: python3 tools/gen_font_blob.py and commit the result")
        return 1
    print("gen_font_blob: up to date")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify freshness, write nothing")
    ns = ap.parse_args()
    return check() if ns.check else generate()


if __name__ == "__main__":
    sys.exit(main())
