#!/usr/bin/env python3
"""gen_assets.py — 图片母版 → 多分辨率 LVGL C 数组(P3,编译期下采样)。

母版 PNG 放 assets_src/images/(符号名同名);本脚本按 ASSET_RESOLUTIONS
生成 SquareLine 兼容的 C 文件:
    images/      → 360(与历史数组逐字节一致,数据层)
    images_r240/ → 240
    images_r466/ → 466
生成文件自带 CONFIG_OBD_UI_RENDER_RES 守卫(未定义时默认 360,
sim/tests 无需配置),三个目录同时参与编译、gc-sections 裁剪。
非 360 目标用 LANCZOS 缩放;母版尺寸等于目标时跳过缩放保证字节可逆。

用法:
    python3 tools/gen_assets.py            # 按 SHA 缓存生成
    python3 tools/gen_assets.py --check    # CI 校验新鲜度(不写文件)
    python3 tools/gen_assets.py --extract  # 一次性引导:从现有 C 数组反解母版
"""
import argparse
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTER_DIR = ROOT / "assets_src" / "images"
OUT_DIRS = {
    360: ROOT / "main/export_path/images",
    240: ROOT / "main/export_path/images_r240",
    466: ROOT / "main/export_path/images_r466",
}
ASSET_RESOLUTIONS = (240, 360, 466)
GENERATED_MARKER = "Auto-generated by gen_assets.py"
TEMPLATE_VERSION = "v4"   # bump when render_c output format changes (v4: LVGL9 image dsc)

# symbol → (color format, 等比缩放 or 精确目标尺寸)
# RGB565_SWAPPED: 2B/px 大端 RGB565(与 v8 TRUE_COLOR 数据布局一致);
# ARGB8888: 4B/px v9 内存序 B,G,R,A(替代 v8 的 3B/px TRUE_COLOR_ALPHA——
# v9 无交错 alpha 的 16bit 格式,RGB565A8 是平面布局,直接换成 32bit 更稳)
ASSETS = {
    "imgRpmFlash1": "RGB565_SWAPPED",
    "imgRpmFlash2": "RGB565_SWAPPED",
    "imgRpmFlash3": "RGB565_SWAPPED",
    "imgBootLogoCustom": "RGB565_SWAPPED",
    "ui_img_pngblackear_png": "ARGB8888",
}


def parse_c_array(text, symbol):
    """提取 <symbol>_map/_data 的字节数组。"""
    m = re.search(
        rf"(?:uint8_t|uint16_t|lv_color_t)\s+{re.escape(symbol)}_(?:map|data)\[\]\s*=\s*\{{(.*?)\}};",
        text, re.S)
    if not m:
        raise RuntimeError(f"array for {symbol} not found")
    return bytes(int(b, 16) for b in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(1)))


def parse_c_dims(text, symbol):
    m = re.search(
        rf"lv_img_dsc_t\s+{re.escape(symbol)}\s*=\s*\{{(.*?)\}};", text, re.S)
    w = re.search(r"\.header\.w\s*=\s*(\d+)", m.group(1))
    h = re.search(r"\.header\.h\s*=\s*(\d+)", m.group(1))
    return int(w.group(1)), int(h.group(1))


def bytes_to_pil(data, w, h, cf):
    from PIL import Image
    if cf == "TRUE_COLOR":
        img = Image.new("RGB", (w, h))
        px = img.load()
        for y in range(h):
            for x in range(w):
                o = (y * w + x) * 2
                v = (data[o] << 8) | data[o + 1]
                px[x, y] = ((v >> 11) << 3, ((v >> 5) & 0x3F) << 2, (v & 0x1F) << 3)
        return img
    img = Image.new("RGBA", (w, h))
    px = img.load()
    for y in range(h):
        for x in range(w):
            o = (y * w + x) * 4
            px[x, y] = (data[o + 2], data[o + 1], data[o], data[o + 3])   # B,G,R,A
    return img


def pil_to_bytes(img, cf):
    w, h = img.size
    out = bytearray()
    if cf == "TRUE_COLOR":
        for r, g, b in img.convert("RGB").getdata():
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out += bytes(((v >> 8) & 0xFF, v & 0xFF))
    else:
        for r, g, b, a in img.convert("RGBA").getdata():
            out += bytes((b, g, r, a))
    return w, h, bytes(out)


def render_c(symbol, cf, w, h, data, res):
    """SquareLine 风格 C 文件(带分辨率守卫与 SHA 头)。"""
    src_sha = hashlib.sha256(
        (MASTER_DIR / f"{symbol}.png").read_bytes()).hexdigest()[:16]
    guard = f"""// {GENERATED_MARKER} — do not edit (masters live in assets_src/images/)
// master: {symbol}.png  sha256:{src_sha}  template:{TEMPLATE_VERSION}  target render res: {res}
#if defined(__has_include)
#if __has_include("sdkconfig.h")
#include "sdkconfig.h"
#endif
#endif
#ifndef CONFIG_OBD_UI_RENDER_RES
#define CONFIG_OBD_UI_RENDER_RES 360   /* simulator / unit tests */
#endif
#if CONFIG_OBD_UI_RENDER_RES == {res}

"""
    bpp = 4 if cf == "ARGB8888" else 2
    chunks = [", ".join(f"0x{b:02X}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    array_body = "  " + ",\n  ".join(chunks)
    tail = f"""

const lv_image_dsc_t {symbol} = {{
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_{cf},
  .header.w = {w},
  .header.h = {h},
  .header.stride = {w} * {bpp},
  .data_size = sizeof({symbol}_data),
  .data = {symbol}_data,
}};

#endif /* CONFIG_OBD_UI_RENDER_RES == {res} */
"""
    return (guard + INCLUDE_BLOCK +
            f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {symbol}_data[] = {{\n"
            + array_body + "\n};" + tail)


INCLUDE_BLOCK = """#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

"""


def check():
    """--check:零第三方依赖(与 gen_font_blob --check 同模式)——校验每个目标
    文件存在且头部记录的母版 SHA / 模板版本与当前一致。生成内容已入库,
    母版或模板一变头部即失配;完整重渲染(需 Pillow)只在真正 apply 时跑。"""
    problems = []
    for symbol in ASSETS:
        master = MASTER_DIR / f"{symbol}.png"
        if not master.exists():
            problems.append(f"missing master: {master.relative_to(ROOT)}")
            continue
        sha = hashlib.sha256(master.read_bytes()).hexdigest()[:16]
        for res in ASSET_RESOLUTIONS:
            out = OUT_DIRS[res] / f"{symbol}.c"
            if not out.exists():
                problems.append(f"missing: {out.relative_to(ROOT)}")
                continue
            text = out.read_text()
            if f"sha256:{sha}" not in text or f"template:{TEMPLATE_VERSION}" not in text:
                problems.append(f"stale: {out.relative_to(ROOT)} "
                                f"(master sha or template version mismatch)")
    if problems:
        print("\n".join(problems))
        print("run tools/gen_assets.py and commit the result")
        return 1
    print("gen_assets: up to date")
    return 0


def masters_fresh():
    """生成模式(apply)的免 Pillow 快路径:全部命中则无需 Pillow。"""
    for symbol in ASSETS:
        master = MASTER_DIR / f"{symbol}.png"
        if not master.exists():
            return False
        sha = hashlib.sha256(master.read_bytes()).hexdigest()[:16]
        for res in ASSET_RESOLUTIONS:
            out = OUT_DIRS[res] / f"{symbol}.c"
            if not out.exists():
                return False
            text = out.read_text()
            if f"sha256:{sha}" not in text or f"template:{TEMPLATE_VERSION}" not in text:
                return False
    return True


def generate(apply=True):
    if masters_fresh():
        print("gen_assets: up to date (sha fast-path)")
        return []
    # 有母版变更/生成物缺失 → 真正重渲染(需要 Pillow)
    from PIL import Image
    problems = []
    for symbol, cf in ASSETS.items():
        master_path = MASTER_DIR / f"{symbol}.png"
        if not master_path.exists():
            problems.append(f"missing master: {master_path.relative_to(ROOT)}")
            continue
        master = Image.open(master_path)
        for res in ASSET_RESOLUTIONS:
            scale = res / 360.0
            if abs(scale - 1.0) < 1e-9:
                img = master
            else:
                img = master.resize((max(1, round(master.width * scale)),
                                     max(1, round(master.height * scale))),
                                    Image.LANCZOS)
            w, h, data = pil_to_bytes(img, cf)
            text = render_c(symbol, cf, w, h, data, res)
            out = OUT_DIRS[res] / f"{symbol}.c"
            if not apply:
                if not out.exists() or out.read_text() != text:
                    problems.append(f"stale: {out.relative_to(ROOT)}")
                continue
            out.parent.mkdir(parents=True, exist_ok=True)
            if not out.exists() or out.read_text() != text:
                out.write_text(text)
                print(f"  wrote {out.relative_to(ROOT)} ({w}x{h}, {len(data)} B)")
    return problems


def extract():
    """一次性引导:从现有 C 数组反解母版 PNG(360 基准)。"""
    MASTER_DIR.mkdir(parents=True, exist_ok=True)
    for symbol, cf in ASSETS.items():
        src = OUT_DIRS[360] / f"{symbol}.c"
        text = src.read_text()
        data = parse_c_array(text, symbol)
        w, h = parse_c_dims(text, symbol)
        expected = w * h * (4 if cf == "ARGB8888" else 2)
        if len(data) != expected:
            raise RuntimeError(f"{symbol}: data {len(data)} != expected {expected}")
        img = bytes_to_pil(data, w, h, cf)
        out = MASTER_DIR / f"{symbol}.png"
        img.save(out)
        print(f"  extracted {out.relative_to(ROOT)} ({w}x{h})")
    print("extraction done — verify with: python3 tools/gen_assets.py --check")


def verify_roundtrip():
    """生成后校验 @360 数据数组与迁移前的原文件逐字节一致(金图零差异前提)。"""
    ok = True
    for symbol, cf in ASSETS.items():
        out = OUT_DIRS[360] / f"{symbol}.c"
        text = out.read_text()
        data = parse_c_array(text, symbol)
        w, h = parse_c_dims(text, symbol)
        img = bytes_to_pil(data, w, h, cf)
        _, _, data2 = pil_to_bytes(img, cf)
        same = data == data2
        ok &= same
        print(f"  {symbol}: roundtrip {'OK' if same else 'MISMATCH'} ({len(data)} B)")
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify freshness, write nothing")
    ap.add_argument("--extract", action="store_true", help="bootstrap masters from existing arrays")
    ap.add_argument("--verify-roundtrip", action="store_true")
    ns = ap.parse_args()

    if ns.extract:
        extract()
        return 0
    if ns.check:
        return check()
    problems = generate(apply=True)
    if ns.verify_roundtrip and not verify_roundtrip():
        return 1
    if problems:
        print("\n".join(problems))
        print("run tools/gen_assets.py and commit the result")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
