#!/usr/bin/env python3
"""gen_fonts.py — Conthrax OTF → 多分辨率 LVGL 字体(P4,编译期下采样)。

源字体 fonts/Conthrax-SemiBold.otf(8 款均为同字重,原文件头 Opts 佐证);
按 720 母版字号在每档渲染分辨率下真光栅化(lv_font_conv,经 npx):
    fonts/      → 360(替换 SquareLine 时代产物,符号/文件名不变)
    fonts_r240/ → 240
    fonts_r466/ → 466
生成文件自带 CONFIG_OBD_UI_RENDER_RES 守卫(未定义默认 360)。
参数复刻原 Opts:--bpp 4 --no-compress --no-prefilter -r 0x20-0x7f,
Size140 仅 0123456789NR。

需要 node/npx(仅生成时);--check 只看头部标记(OTF sha + 模板版本),
CI 可免 node 运行。用法:
    python3 tools/gen_fonts.py            # 生成(需 npx,首次联网)
    python3 tools/gen_fonts.py --check    # 新鲜度校验,只读
"""
import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_SOURCE = ROOT / "fonts" / "Conthrax-SemiBold.otf"
OUT_DIRS = {
    360: ROOT / "main/export_path/fonts",
    240: ROOT / "main/export_path/fonts_r240",
    466: ROOT / "main/export_path/fonts_r466",
}
RESOLUTIONS = (240, 360, 466)
TEMPLATE_VERSION = "v2"   # bump when guard/header format changes
GENERATED_MARKER = "Auto-generated by gen_fonts.py"

# 720 母版字号(= 360 时代值 ×2);140 为仪表大字(数字+N+R 子集)
FONT_MASTER_SIZES = {
    "ui_font_FontTypoderSize16": 32,
    "ui_font_FontTypoderSize20": 40,
    "ui_font_FontTypoderSize24": 48,
    "ui_font_FontTypoderSize36": 72,
    "ui_font_FontTypoderSize40": 80,
    "ui_font_FontTypoderSize44": 88,
    "ui_font_FontTypoderSize56": 112,
    "ui_font_FontTypoderSize140": 280,
}
SYMBOLS_SUBSET = {"ui_font_FontTypoderSize140": "0123456789NR"}


def target_px(master_px, res):
    return max(8, int(master_px * res / 720 + 0.5))


def wrap_guard(text, symbol, master_px, res, otf_sha):
    header = (
        f"// {GENERATED_MARKER} — do not edit (source: fonts/Conthrax-SemiBold.otf)\n"
        f"// master px:{master_px}  sha256:{otf_sha}  template:{TEMPLATE_VERSION}  "
        f"target render res: {res} (size {target_px(master_px, res)})\n"
        "#ifndef CONFIG_OBD_UI_RENDER_RES\n"
        "#define CONFIG_OBD_UI_RENDER_RES 360   /* simulator / unit tests */\n"
        "#endif\n"
        f"#if CONFIG_OBD_UI_RENDER_RES == {res}\n\n"
        "#ifdef __has_include\n"
        "    #if __has_include(\"lvgl.h\")\n"
        "        #ifndef LV_LVGL_H_INCLUDE_SIMPLE\n"
        "            #define LV_LVGL_H_INCLUDE_SIMPLE\n"
        "        #endif\n"
        "    #endif\n"
        "#endif\n\n"
    )
    footer = f"\n#endif /* CONFIG_OBD_UI_RENDER_RES == {res} */\n"
    # 去掉 lv_font_conv 自带的 Opts 头注释;tmp 文件名会污染符号/守卫宏(大小写两种形态),精确还原
    text = re.sub(r"^/\*+[\s\S]*?\*+/\s*\n", "", text, count=1)
    text = text.replace(f".{symbol}.tmp", symbol)
    text = text.replace(f".{symbol.upper()}.TMP", symbol.upper())
    return header + text + footer


def generate():
    if not FONT_SOURCE.exists():
        print(f"missing font source: {FONT_SOURCE}")
        return 1
    otf_sha = hashlib.sha256(FONT_SOURCE.read_bytes()).hexdigest()[:16]

    for res in RESOLUTIONS:
        for symbol, master_px in FONT_MASTER_SIZES.items():
            size = target_px(master_px, res)
            out_dir = OUT_DIRS[res]
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path = out_dir / f"{symbol}.c"
            tmp = out_dir / f".{symbol}.tmp.c"

            cmd = ["npx", "--yes", "lv_font_conv", "--font", str(FONT_SOURCE),
                   "--size", str(size), "--bpp", "4", "--format", "lvgl",
                   "--no-compress", "--no-prefilter", "-o", str(tmp)]
            if symbol in SYMBOLS_SUBSET:
                cmd += ["--symbols", SYMBOLS_SUBSET[symbol]]
            else:
                cmd += ["-r", "0x20-0x7f"]

            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode != 0:
                print(f"lv_font_conv failed for {symbol}@{res}:\n{r.stdout}{r.stderr}")
                return 1
            text = wrap_guard(tmp.read_text(), symbol, master_px, res, otf_sha)
            tmp.unlink()
            if not out_path.exists() or out_path.read_text() != text:
                out_path.write_text(text)
                print(f"  wrote {out_path.relative_to(ROOT)} (size {size})")
    print("gen_fonts: generation done")
    return 0


def check():
    otf_sha = hashlib.sha256(FONT_SOURCE.read_bytes()).hexdigest()[:16]
    problems = []
    for res in RESOLUTIONS:
        for symbol, master_px in FONT_MASTER_SIZES.items():
            out = OUT_DIRS[res] / f"{symbol}.c"
            if not out.exists():
                problems.append(f"missing: {out.relative_to(ROOT)}")
                continue
            text = out.read_text()
            for needle in (f"sha256:{otf_sha}", f"template:{TEMPLATE_VERSION}",
                           f"target render res: {res}"):
                if needle not in text:
                    problems.append(f"stale: {out.relative_to(ROOT)} (no {needle})")
                    break
    if problems:
        print("\n".join(problems))
        print("run: python3 tools/gen_fonts.py  (needs node/npx) and commit the result")
        return 1
    print("gen_fonts: up to date")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ns = ap.parse_args()
    return check() if ns.check else generate()


if __name__ == "__main__":
    sys.exit(main())
